### ISSUE TITLE
Javascript Error

### ISSUE THREAD

**Issue by PryPurity** [aza547/wow-recorder#69] opened 2022-09-03 23:48 UTC
All I did was just install the software, set it up, then I closed the application while I had World of Warcraft running.

Running:
Windows 11
AMD Graphics

![image](https://user-images.githubusercontent.com/9400821/188290233-bc1823fa-2e2a-49b0-8c1d-b2261ec2334c.png)

**Comment by aza547** [comment] 2022-09-04 08:03
This is caused by closing the app following it failing to start up. If you open it, get the config set up, then close it (the error will appear first time). Re-open it to pick up the new config. Assuming the config is valid, you shouldn't see this again.

There is a proper fix in the release coming today. Thanks for reporting.

**Comment by aza547** [comment] 2022-09-04 09:04
Fixed in 2.6.0. Closing.

**Closed by aza547** 2022-09-04 09:04 UTC
Labels: bug
