### ISSUE TITLE
Failed to launch, fix config and restart

### ISSUE THREAD

**Issue by jgorset** [aza547/wow-recorder#23] opened 2022-08-02 13:20 UTC
Hi! Really looking forward to using this, but having an issue with getting it up and running.

![image](https://user-images.githubusercontent.com/195266/182384692-a9bc1cc8-61a7-4c2b-a15f-31e4014801ed.png)

This _should_ work, right? All these paths exist, and I did relaunch it, yet it keeps giving me the same error. Is there something I should be looking out for?

**Comment by jgorset** [comment] 2022-08-02 15:56
That's weird, after a few hours now it's changed to "waiting for a game to start", which seems promising! In the mean time, I installed Obs by itself (figuring maybe it was a prerequisite) and updated Windows with some minor patches. Maybe one of those things fixed it?

**Comment by aza547** [comment] 2022-08-02 21:39
Thanks for the report. I had a bug recently that the recording would fail to start if there was no combatlog files in the logs directory. I thought I had fixed it but I wonder if that could be the cause. 

Is it possible that you have never used combatlogging before and thus had no combatlog files present initially? If so I'd like to re-open this to make a proper fix!

Windows updates or OBS installation are unlikely to be the difference here.

**Comment by aza547** [comment] 2022-08-02 21:44
Your config looks good fyi, and the waiting for the game to start is the working state.

If you're tech savvy you could check our the python scripts under the test folder, they are very basic and would let you test it out with minor modifications to the script without even opening WoW (or alternatively just queue up for a skirmish)!

Suspect it's the no combat log files thing and you have indirectly created some by either installing the SCL addon or typing /combatlog.

**Comment by aza547** [comment] 2022-08-05 21:29
I'm opening this again - I should investigate this. It sucks if new users get hit with this (especially if above is correct and it's already diagnosed!).

**Comment by jgorset** [comment] 2022-08-06 08:42
Sorry for my late reply! I'm pretty sure it's exactly as you said -- I didn't have combat logs prior to installing this, so there weren't any in the directory, and that probably caused the error message!

**Comment by aza547** [comment] 2022-08-20 09:45
Still want to fix this, it's a crap first time user experience.

**Comment by aza547** [comment] 2022-08-31 20:00
Are you sure? This issue is worked around by closing and re-opening the application. It shouldn't appear again after that. Sounds like it might be another issue?

**Comment by computerchipdotbiz** [comment] 2022-08-31 20:06
I am VERY sure, also, when I go to close it from the system tray, it throws this error every time as well. 



![wcr](https://user-images.githubusercontent.com/5994477/187772038-9942831e-34f3-42d3-8db0-3e012f1bee6e.png)

**Comment by aza547** [comment] 2022-08-31 20:08
Aware of this one actually. I'll make a fix for that. 

Ah, I am confused between tickets here. So the problem is no logs. We have a fix in the works for that. If you leave a combat log in place you should be able to get past it. Are you manually deleting combat logs?

**Comment by computerchipdotbiz** [comment] 2022-08-31 20:11
> Ah aware of the one cleanupBuffer one actually. I'll make a fix for that.
> 
> Ah, I am confused between tickets here. So the problem is no logs. We have a fix in the works for that. If you leave a combat log in place you should be able to get past it. Are you manually deleting combat logs?

I don't even know what/where combat logs are, so probably not manually doing anything with them. Sorry I am not much more help.

**Comment by computerchipdotbiz** [comment] 2022-08-31 20:18
I did not have that installed. I installed it and opened WoW, enabled it, restarted WCR twice, still have the error.  Do I need to play a BG first?

**Comment by aza547** [comment] 2022-08-31 20:20
You just need a combatlog to be present when the app starts, if you fight a mob with combat logging enabled it will create one, alternatively you could just create an empty file with the right name in the right place. Example below.

![image](https://user-images.githubusercontent.com/32389325/187774407-5a7df932-d20c-45da-a1fe-6aad24876743.png)

**Comment by computerchipdotbiz** [comment] 2022-08-31 20:28
I dropped down into the maw and fought a couple of mobs, no combat log, exited from resting area, no log.  I created it manually and it seems to have resolved the issue with WCRs config error fix and restart issue, now it says waiting for WoW to start.  

Thanks!

**Comment by aza547** [comment] 2022-08-31 20:29
Depending on the option you went with for combatlogging the addons will only combat log in specific scenarios (you should check their config).  Suspect that's why you didn't get a combatlog fighting in the maw.

**Comment by aza547** [comment] 2022-09-03 21:34
Fixed on main, will be in next release.

**Comment by aza547** [comment] 2022-09-04 09:14
Fixed in 2.6.0, closing.

**Closed by aza547** 2022-09-04 09:14 UTC
Labels: bug, help wanted, good first issue
