### ISSUE TITLE
A Javascript error occurred

### ISSUE THREAD

**Issue by ddechant** [aza547/wow-recorder#134] opened 2022-09-21 02:20 UTC
I get the follow error after running the application while in a raid instance. Logging was already enabled.

![image](https://user-images.githubusercontent.com/263218/191399700-163742d8-c6cf-4e6a-a075-1f39ecca460b.png)

**Comment by tdaugaard** [comment] 2022-09-21 08:05
Would you happen to have the combat log that caused this and would you be willing to share it either here or in a DM on Discord so I can replay it and see if I can reproduce the error?

**Comment by ddechant** [comment] 2022-09-22 03:50
Sent you the combat logs in discord.

**Comment by tdaugaard** [comment] 2022-09-22 08:29
Ah, I see! Thanks a lot - a player died before the raid encounter started and because of that, it was trying to access a timestamp of then the video started recording, but that hadn't been set yet - only set when something starts.

The fix is of course to only handle unit deaths when something is in progress.

**Comment by aza547** [comment] 2022-09-22 18:54
Fixed in next release.

**Closed by aza547** 2022-09-22 18:54 UTC
Labels: bug
